services:
  - type: web
    name: smartscheduler
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Development
      - key: Database__Provider
        value: Sqlite
      - key: Database__ApplyMigrationsOnStartup
        value: true
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/tmp/smartscheduler.db
